### ISSUE TITLE
Symfony 4.2 Deprecation Warnings

### ISSUE THREAD

**Issue by mab05k** [Behat/Behat#1202]
Since Symfony 4.2 was released, there have been deprecations created in the Translation Component. The deprecated methods are being called from `Behat\Behat\Output\Node\Printer\CounterPrinter`

```
php.INFO: User Deprecated: The "Symfony\Component\Translation\Translator::transChoice()" method is deprecated since Symfony 4.2, use the trans() one instead with a "%count%" parameter. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Symfony\\Component\\Translation\\Translator::transChoice()\" method is deprecated since Symfony 4.2, use the trans() one instead with a \"%count%\" parameter. at /srv/vendor/symfony/translation/Translator.php:229)"} []
```
The also recommend switching over to the Contracts Library `Symfony\Contracts\Translation\TranslatorInterface`

Are there any plans to fix this warning? I imagine this would probably be a breaking change since it would require at least upgrading to PHP 7.1+ (requirement from Contracts package)

I'm happy to submit a PR with the updates to fix these warnings (assuming its not far more complicated than updating these method calls), just let me know your concerns regarding backwards compatibility.

**Comment by ciaranmcnulty** [comment]
In the past we've handled things like this without BC breaks by detecting the new API is available and using it if so, but leaving the old code in as well.

If you can do the switch at the DI level (i.e. have two implementations of the caller), all the better

**Comment by TerjeBr** [comment]
Hi. Any progress on this? Or do you need someone else to pick this up?

**Comment by mab05k** [comment]
I have not looked at this in quite some time, since the build was breaking (since my last comments). I don't have time right now to continue working on it.

**Comment by pamil** [comment]
Should be fixed since Behat supports Symfony 5 already.

**Comment by miedzikd** [comment]
Hej Kamil :) 
> Should be fixed since Behat supports Symfony 5 already.
Hmm... but `transChoice`  is deprecated since Symfony 4.2 ... If I understand you correctly, this error still will be visible for people who using Symfony 4?

**Comment by guilliamxavier** [comment]
@miedzikd: I just submitted #1311 for Symfony 4

**Comment by miedzikd** [comment]
Thank you soo much @guilliamxavier  :)
