### ISSUE TITLE
PHP Deprecated:  The ability to pass file names to Yaml::parse() was deprecated in 2.7

### ISSUE THREAD

**Issue by canfiax** [Behat/Behat#689]
When running behat, getting error:

    PHP Deprecated:  The ability to pass file names to Yaml::parse() was deprecated in 2.7 and will be 
    removed in 3.0. Please, pass the contents of the file instead. in  
    /vendor/symfony/yaml/Symfony/Component/Yaml/Yaml.php on line 58

Whats up?

**Comment by canfiax** [comment]
Fixed here: https://github.com/Behat/Behat/commit/7192c4eb862b0a82a6dd19501d9b3b4dc1aa86ef

**Comment by cauerego** [comment]
Still getting the exact same error, except it says "deprecated in 2.2" and comes as a warning (so, not really an error).

I'm on a mac, if it's any relevant. Not sure how to find the file from the fix above, I believe it's compiled in the binary and can't verify my binary version, maybe due to #475 .

Maybe I got an outdated version, somehow?

**Comment by stof** [comment]
Which version of Behat are you using ?

If it is installed through composer, use ``composer show -i behat/behat`` to show the info about the installed version of the package

**Comment by cauerego** [comment]
Thanks for the hint!

I've never heard of Behat, Mink or Composer before installing all of them using [this guide](https://pantheon.io/docs/guides/automated-testing-wordpress-behat/). It is 2.4.6 I think. PHP 5.3 and gherkin 2.2.9 are clear. And I actually had to use `php composer.phar show -i behat/behat`. My `composer.json` had this: `"behat/behat": "2.4.*@stable",`

Now [I'm trying to see](https://github.com/ari-gold/WordPress-Behat-Quickstart/issues/1) how to properly update this... Since this fix is for version 3.

**Comment by stof** [comment]
Behat 2.4 is more than 2 years old. This version is not maintained anymore and has indeed not been updated to avoid deprecations.

Use either Behat 2.5 or 3 (both have been fixed)

**Comment by stof** [comment]
Regarding ``composer`` vs ``php composer.phar``, it is a matter of having composer available globally in your system, or downloading it in the project. I always use a global composer, which is why I give it this way
